title: "Cascade Symmetry"
description: "Weekly notes, schedules, and illustrations."

# Replace "theme:" with these two lines:
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

# Navigation settings
search_enabled: true
nav_sort: nav_order
