title: "Cascade 2026 The Magic of Symmetry"
description: "Weekly notes, schedules, and illustrations."

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

# Navigation settings
search_enabled: true
nav_sort: nav_order
